db:
  image: postgres
  environment:
    - PGHOST=db
    - PGUSER=postgres
    - PGPASSWORD=postgres
api:
  image: studentmediene/radiorevolt-api-dev:latest
  entrypoint: "npm start"
  ports:
      - "9000:9000"
  links:
    - db
  environment:
    - PG_URL=postgres://postgres:postgres@db/postgres
    - NODE_ENV=development
